Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.hostname = "twin-ubuntu"
  config.vm.network "private_network", type: "dhcp"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
  config.vm.synced_folder "./bash_scripts", "/vagrant/scripts"

  config.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y dos2unix

    dos2unix /vagrant/scripts/install_tools.sh

    chmod +x /vagrant/scripts/install_tools.sh
    /vagrant/scripts/install_tools.sh
    exec $SHELL
    SHELL
  end
end
