common_vagrantfile = File.join(Dir.pwd, '../shared/commons/Vagrantfile.common')
load common_vagrantfile if File.exist?(common_vagrantfile)
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # Every Vagrant virtual environment requires a box to build.
    config.vm.box = "vbt/debian12"
    config.vm.box_version = "0.1.0"

    config.vm.disk :disk, size: "80GB", name: "vagrant_disk"
    config.disksize.size = "80GB" # vagrant plugin install vagrant-disksize

    config.vm.define "VM_vbt_cache"

    # Create a private network, which allows host-only access to the machine using DHCP.
    # Static ip might easy deployment later on?
    config.vm.network "public_network", use_dhcp_assigned_default_route: true

    config.vm.synced_folder File.join(Dir.pwd, "../shared"), "/home/vagrant/shared"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "VM_vbt_cache"

        # Customize the amount of memory: MB on the VM:
        vb.memory = "10240"

        #number of cpus
        vb.cpus = "8"
    end

    # Define the bootstrap file: A (shell) script that runs after first setup of your box (= provisioning)
    config.vm.provision "shell" do |shell|
        shell.path = "../shared/cache_scripts/create_cache.sh"
        shell.env = {
            BUILDCACHE_OCI_USERNAME:Shellwords.escape(ENV['BUILDCACHE_OCI_USERNAME']),
            BUILDCACHE_OCI_PASSWORD:Shellwords.escape(ENV['BUILDCACHE_OCI_PASSWORD']),
            BUILDCACHE_OCI_HOST:Shellwords.escape(ENV['BUILDCACHE_OCI_HOST']),
            BUILDCACHE_OCI_PROJECT:Shellwords.escape(ENV['BUILDCACHE_OCI_PROJECT']),
            BUILDCACHE_OCI_VERSION:Shellwords.escape(ENV['BUILDCACHE_OCI_VERSION']),

            CONCRETIZE_OCI_USERNAME:Shellwords.escape(ENV['CONCRETIZE_OCI_USERNAME']),
            CONCRETIZE_OCI_PASSWORD:Shellwords.escape(ENV['CONCRETIZE_OCI_PASSWORD']),
            CONCRETIZE_OCI_HOST:Shellwords.escape(ENV['CONCRETIZE_OCI_HOST']),
            CONCRETIZE_OCI_PROJECT:Shellwords.escape(ENV['CONCRETIZE_OCI_PROJECT']),
            CONCRETIZE_OCI_VERSION:Shellwords.escape(ENV['CONCRETIZE_OCI_VERSION']),

            VBT_SPACK_ENV_ACCESS_TOKEN:Shellwords.escape(ENV['VBT_SPACK_ENV_ACCESS_TOKEN']),
        }
    end

end