common_vagrantfile = File.join(Dir.pwd, '../shared/commons/Vagrantfile.common')
load common_vagrantfile if File.exist?(common_vagrantfile)
# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # Every Vagrant virtual environment requires a box to build.
    config.vm.box = "bento/ubuntu-22.04"
    config.vm.box_version = "202502.21.0"

    config.vm.define "VM_vbt_cache"

    # Create a private network, which allows host-only access to the machine using DHCP.
    # Static ip might easy deployment later on?
    config.vm.network "private_network", type: "dhcp"
    config.vm.synced_folder File.join(Dir.pwd, "../shared"), "/home/vagrant/shared"

    config.vm.provider "virtualbox" do |vb|
        vb.name = "VM_vbt_cache"

        # Customize the amount of memory: MB on the VM:
        vb.memory = "16384"

        #number of cpus
        vb.cpus = "12"

    config.vm.boot_timeout = 86400  # 24h
    config.disksize.size = "100GB" # vagrant plugin install vagrant-disksize


    end

    # Define the bootstrap file: A (shell) script that runs after first setup of your box (= provisioning)
    config.vm.provision "shell" do |shell|
        shell.path = "../shared/cache_scripts/create_cache.sh"
        shell.env = {
            BUILDCACHE_OCI_USERNAME:Shellwords.escape(ENV['BUILDCACHE_OCI_USERNAME']),
            BUILDCACHE_OCI_PASSWORD:Shellwords.escape(ENV['BUILDCACHE_OCI_PASSWORD']),
            BUILDCACHE_OCI_HOST:Shellwords.escape(ENV['BUILDCACHE_OCI_HOST']),
            BUILDCACHE_OCI_PROJECT:Shellwords.escape(ENV['BUILDCACHE_OCI_PROJECT']),

            CONCRETIZE_OCI_USERNAME:Shellwords.escape(ENV['CONCRETIZE_OCI_USERNAME']),
            CONCRETIZE_OCI_PASSWORD:Shellwords.escape(ENV['CONCRETIZE_OCI_PASSWORD']),
            CONCRETIZE_OCI_HOST:Shellwords.escape(ENV['CONCRETIZE_OCI_HOST']),
            CONCRETIZE_OCI_PROJECT:Shellwords.escape(ENV['CONCRETIZE_OCI_PROJECT']),
        }
    end

end