common_vagrantfile = File.join(Dir.pwd, '../shared/commons/Vagrantfile.common')
load common_vagrantfile if File.exist?(common_vagrantfile)

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    # Every Vagrant virtual environment requires a box to build.
    config.vm.box = "ubuntu/focal64"

    config.vm.define "VM_twin"

    # Create a private network, which allows host-only access to the machine using DHCP.
    # Static ip might easy deployment later on?
    # forwarded_port in order to be able to access jupyter lab from the VM
    config.vm.network "forwarded_port", type: "dhcp", guest: 8888, host: 8888
    config.vm.synced_folder File.join(Dir.pwd, "../shared"), "/home/vagrant/shared"

    config.vm.provider "virtualbox" do |vb|
        # name of the VirtualBox GUI
        vb.name = "VM_twin"

        # Customize the amount of memory on the VM:
        vb.memory = "2048"

        #number of cpus
        vb.cpus = "2"

  config.vm.boot_timeout = 86400  # 24h
  end

  # Define the bootstrap file: A (shell) script that runs after first setup of your box (= provisioning)
  config.vm.provision "shell" do |shell|
    shell.path = "../shared/install.sh"
    shell.env = {
        REGISTRY_USERNAME:Shellwords.escape(ENV['REGISTRY_USERNAME']),
        REGISTRY_PASSWORD:Shellwords.escape(ENV['REGISTRY_PASSWORD']),
        REGISTRY_HOST:Shellwords.escape(ENV['REGISTRY_HOST']),
        REGISTRY_PROJECT:Shellwords.escape(ENV['REGISTRY_PROJECT']),
        REGISTRY_CACHE_VERSION:Shellwords.escape(ENV['REGISTRY_CACHE_VERSION'])
    }
  end

end