stages:
  - test
  - build
  - release

variables:
  DEBIAN_FRONTEND: noninteractive
  BOX_NAME: "vbt_debian12.box"

test-create-cache:
  rules:
    - if: '$CI_COMMIT_BRANCH != "master" && $CI_COMMIT_BRANCH != "dev"'
      when: always
    - when: never
  image: python:3.11
  stage: test
  timeout: 1 hours
  tags:
    - $DOCKER_RUNNER_TAG
  before_script:
    - chmod +x ./installation/local/shared/commons/bootstrap.sh
    - ./installation/local/shared/commons/bootstrap.sh
  script:
    - chmod +x ./installation/local/shared/vbt.sh
    - ./installation/local/shared/vbt.sh "create_cache.py" "./installation/local/"

test-use-cache:
  environment:
    name: testing
  rules:
    - if: '$CI_COMMIT_BRANCH != "master" && $CI_COMMIT_BRANCH != "dev"'
      when: always
    - when: never
  image: python:3.11
  stage: test
  timeout: 1 hours
  tags:
    - $DOCKER_RUNNER_TAG
  before_script:
    - chmod +x ./installation/local/shared/commons/bootstrap.sh
    - ./installation/local/shared/commons/bootstrap.sh
  script:
    - chmod +x ./installation/local/shared/vbt.sh
    - ./installation/local/shared/vbt.sh "use_cache.py" "./installation/local/"

build-cache:
  environment:
    name: caching
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
      when: always
    - when: never
  image: python:3.11
  stage: build
  timeout: 24 hours
  tags:
    - $DOCKER_RUNNER_TAG
  before_script:
    - chmod +x ./installation/local/shared/commons/bootstrap.sh
    - ./installation/local/shared/commons/bootstrap.sh
  script:
    - chmod +x ./installation/local/shared/vbt.sh
    - ./installation/local/shared/vbt.sh "create_cache.py" "./installation/local/"

create-box:
  environment:
    name: caching
  image: ubuntu:24.04
  stage: release
  when: manual
  except:
    - tags
  id_tokens:
    SITE_ID_TOKEN:
      aud: "https://gitlab.jsc.fz-juelich.de"
  timeout: 2 hours
  tags:
    - $SHELL_RUNNER_TAG
  before_script:
    # install virtual box on the Ci runner
    - chmod +x ./installation/local/shared/commons/release_tools.sh
    - ./installation/local/shared/commons/release_tools.sh

    - echo "VirtualBox version:"
    - vboxmanage --version

    # install Vagrant on the Ci runner
  script:
    #    - vagrant --version
    - vboxmanage --version

  artifacts:
    paths:
      - $BOX_NAME
    expire_in: 1 week


release:
  needs:
    - job: create-box
      artifacts: true

