stages:
  - build

variables:
  DEBIAN_FRONTEND: noninteractive
  BOX_NAME: "vbt_debian12.box"

build-cache:
  image: python:3.11
  stage: build
  timeout: 14 hours
  tags:
    - $DOCKER_RUNNER_TAG
  before_script:
    - chmod +x ./installation/local/shared/commons/bootstrap.sh
    - ./installation/local/shared/commons/bootstrap.sh
  script:
    - ls --all
    - echo $HOME_PATH
    - chmod +x ./installation/local/shared/vbt.sh
    - ./installation/local/shared/vbt.sh "create_cache.py" "./installation/local/"

create-box:
  image: ubuntu:24.04
  stage: build
  id_tokens:
    SITE_ID_TOKEN:
      aud: "https://gitlab.jsc.fz-juelich.de"
  timeout: 2 hours
  tags:
    - juwels
    - jacamar
    - login
    - shell
  before_script:
    # install virtual box on the Ci runner
    - apt-get update
    - apt-get install -y wget gnupg2 curl lsb-release   software-properties-common
    - echo "Adding VirtualBox GPG key..."
    - wget -q https://www.virtualbox.org/download/oracle_vbox_2016.asc -O- | gpg --dearmor | tee /usr/share/keyrings/virtualbox.gpg > /dev/null
    - echo "deb [arch=amd64 signed-by=/usr/share/keyrings/virtualbox.gpg] https://download.virtualbox.org/virtualbox/debian jammy contrib" > /etc/apt/sources.list.d/virtualbox.list

    - apt-get update
    - apt-get install -y gcc make perl dkms linux-headers-$(uname -r)

    - echo "Installing VirtualBox 7.0.20..."
    - apt-get install -y virtualbox-7.0

    - echo "VirtualBox version:"
    - vboxmanage --version

    # install Vagrant on the Ci runner
  script:
    #    - vagrant --version
    - vboxmanage --version

  artifacts:
    paths:
      - $BOX_NAME
    expire_in: 1 week
#
#  after_script:
#    - vagrant destroy -f
