stages:
  - build
  - release

variables:
  DEBIAN_FRONTEND: noninteractive
  BOX_NAME: "vbt_debian12.box"

build-cache:
  image: python:3.11
  stage: build
  timeout: 14 hours
  tags:
    - $DOCKER_RUNNER_TAG
  before_script:
    - chmod +x ./installation/local/shared/commons/bootstrap.sh
    - ./installation/local/shared/commons/bootstrap.sh
  script:
    - ls --all
    - echo $HOME_PATH
    - chmod +x ./installation/local/shared/vbt.sh
    - ./installation/local/shared/vbt.sh "create_cache.py" "./installation/local/"

create-box:
  image: ubuntu:24.04
  stage: release
  id_tokens:
    SITE_ID_TOKEN:
      aud: "https://gitlab.jsc.fz-juelich.de"
  timeout: 2 hours
  tags:
    - juwels
    - jacamar
    - login
    - shell
  before_script:
    # install virtual box on the Ci runner
    - chmod +x ./installation/local/shared/commons/release_tools.sh
    - ./installation/local/shared/commons/release_tools.sh

    - echo "VirtualBox version:"
    - vboxmanage --version

    # install Vagrant on the Ci runner
  script:
    #    - vagrant --version
    - vboxmanage --version

  artifacts:
    paths:
      - $BOX_NAME
    expire_in: 1 week
#
#  after_script:
#    - vagrant destroy -f
