stages:
  - test
  - build
  - sync
  - release

test-create-cache:
  environment:
    name: testing
  rules:
    - if: '$CI_COMMIT_BRANCH != "master" && $CI_COMMIT_BRANCH != "dev"'
      when: always
    - when: never
  image: ubuntu:24.04
  stage: test
  timeout: 1 hours
  tags:
    - $DOCKER_RUNNER_TAG
  variables:
    DEPLOY_TYPE: "master"
  script:
    - export TMPFILE=$(mktemp)
    - chmod +x ./installation/shared/vbt.sh
    - bash -c 'set -o pipefail && ./installation/shared/vbt.sh "create_cache.py" "./installation/" | tee "$TMPFILE"'
    - mv ./installation/shared/.dedal.log .create_cache.dedal.log
    - mv ./installation/shared/.generate_cache.log .create_cache.generate_cache.log
    - export RESULT=$(grep . "$TMPFILE" | tail -n 2 | head -n 1)
    - mv $TMPFILE .complete_log.txt
    - |
      if [ "$RESULT" != "true" ]; then
       exit 1
      fi
  artifacts:
    paths:
      - .complete_log.txt
      - .create_cache.dedal.log
      - .create_cache.generate_cache.log
    expire_in: 1 week

test-use-cache:
  environment:
    name: testing
  rules:
    - if: '$CI_COMMIT_BRANCH != "master" && $CI_COMMIT_BRANCH != "dev"'
      when: always
    - when: never
  image: ubuntu:24.04
  stage: test
  timeout: 1 hours
  tags:
    - $DOCKER_RUNNER_TAG
  variables:
    DEPLOY_TYPE: "master"
  script:
    - export TMPFILE=$(mktemp)
    - chmod +x ./installation/shared/vbt.sh
    - bash -c 'set -o pipefail && ./installation/shared/vbt.sh "use_cache.py" "./installation/" | tee "$TMPFILE"'
    - mv ./installation/shared/.dedal.log .use_cache.dedal.log
    - mv ./installation/shared/.generate_cache.log .use_cache.generate_cache.log
    - export RESULT=$(grep . "$TMPFILE" | tail -n 2 | head -n 1)
    - mv $TMPFILE .complete_log.txt
    - |
      if [ "$RESULT" != "true" ]; then
       exit 1
      fi
  artifacts:
    paths:
      - .complete_log.txt
      - .use_cache.dedal.log
      - .use_cache.generate_cache.log
    expire_in: 1 week

build-cache-ubuntu-local:
  environment:
    name: caching-ubuntu
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $OPERATION == "cache"'
  image: ubuntu:24.04
  stage: build
  timeout: 72 hours
  tags:
    - $DOCKER_RUNNER_TAG
  variables:
    DEPLOY_TYPE: "local"
    CONCRETIZE_OCI_VERSION: "CONCRETIZE_OCI_VERSION_UBUNTU"
    BUILDCACHE_OCI_VERSION: "BUILDCACHE_OCI_VERSION_UBUNTU"
  script:
    - export TMPFILE=$(mktemp)
    - chmod +x ./installation/shared/vbt.sh
    - bash -c 'set -o pipefail && ./installation/shared/vbt.sh "create_cache.py" "./installation/" | tee "$TMPFILE"'
    - mv ./installation/shared/.dedal.log .build_cache_ubuntu_local.dedal.log
    - mv ./installation/shared/.generate_cache.log .build_cache_ubuntu_local.generate_cache.log
    - export RESULT=$(grep . "$TMPFILE" | tail -n 2 | head -n 1)
    - mv $TMPFILE .complete_log.txt
    - |
      if [ "$RESULT" != "true" ]; then
       exit 1
      fi
  artifacts:
    when: always
    paths:
      - .complete_log.txt
      - .build_cache_ubuntu_local.dedal.log
      - .build_cache_ubuntu_local.generate_cache.log
    expire_in: never

.cleanup-hpc-environment-template:
  environment:
    name: caching-rocky
  variables:
    GIT_STRATEGY: none
  id_tokens:
    SITE_ID_TOKEN:
      aud: "https://gitlab.jsc.fz-juelich.de"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $OPERATION == "cache"'
  timeout: 2 hours
  tags:
    - juwels
    - jacamar
    - login
    - shell
  script:
    - rm -rf /p/scratch/vbt/vbt-spack/vbt_spack_kernel/$KERNEL_VERSION || exit -1

prep-hpc-environment-build:
  stage: build
  extends: .cleanup-hpc-environment-template

build-cache-rocky-hpc:
  environment:
    name: caching-rocky
  variables:
    CUSTOM_CI_BUILDS_DIR: /p/scratch/vbt/vbt-spack/vbt_spack_kernel/$KERNEL_VERSION
    HOME: /p/scratch/vbt/vbt-spack/vbt_spack_kernel/$KERNEL_VERSION
    SPACK_USER_CONFIG_PATH: /p/scratch/vbt/vbt-spack/vbt_spack_kernel/$KERNEL_VERSION
    DEPLOY_TYPE: "hpc"
  id_tokens:
    SITE_ID_TOKEN:
      aud: "https://gitlab.jsc.fz-juelich.de"
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $OPERATION == "cache"'
  stage: build
  timeout: 72 hours
  tags:
    - juwels
    - jacamar
    - login
    - shell
  needs:
    - prep-hpc-environment-build
  script:
    - gcc --version
    - export FULL_PATH=$(pwd)
    - cd $CUSTOM_CI_BUILDS_DIR
    - cp -r $FULL_PATH $CUSTOM_CI_BUILDS_DIR
    - cd virtualbraintwin
    - module load StdEnv/2025
    - export TMPFILE=$(mktemp)
    - chmod +x ./installation/shared/vbt.sh
    - bash -c 'set -o pipefail && ./installation/shared/vbt.sh "create_cache.py" "./installation/" | tee "$TMPFILE"'
    - pwd
    - ls --all
    - cp $CUSTOM_CI_BUILDS_DIR/virtualbraintwin/installation/shared/.dedal.log $CUSTOM_CI_BUILDS_DIR/virtualbraintwin/build_cache_ubuntu_rocky.dedal.log
    - cp $CUSTOM_CI_BUILDS_DIR/virtualbraintwin/installation/shared/.generate_cache.log $CUSTOM_CI_BUILDS_DIR/virtualbraintwin/build_cache_ubuntu_rocky.generate_cache.log
    - export RESULT=$(grep . "$TMPFILE" | tail -n 2 | head -n 1)
    - cp $TMPFILE $CUSTOM_CI_BUILDS_DIR/virtualbraintwin/complete_log.txt
    - ls --all
    - |
      if [ "$RESULT" != "true" ]; then
       exit 1
      fi
  artifacts:
    when: always
    paths:
      - $CUSTOM_CI_BUILDS_DIR/virtualbraintwin/complete_log.txt
      - $CUSTOM_CI_BUILDS_DIR/virtualbraintwin/build_cache_ubuntu_rocky.dedal.log
      - $CUSTOM_CI_BUILDS_DIR/virtualbraintwin/build_cache_ubuntu_rocky.generate_cache.log
    expire_in: never

clean-hpc-environment-build:
  stage: build
  extends: .cleanup-hpc-environment-template
  needs:
    - build-cache-rocky-hpc

prep-hpc-environment-release:
  stage: release
  rules:
    - if: $CI_COMMIT_TAG
  extends: .cleanup-hpc-environment-template

install-vbt-spack-env-hpc:
  environment:
    name: caching-rocky
  variables:
    CUSTOM_CI_BUILDS_DIR: /p/scratch/vbt/vbt-spack/vbt_spack_kernel/$KERNEL_VERSION
    HOME: /p/scratch/vbt/vbt-spack/vbt_spack_kernel/$KERNEL_VERSION
    SPACK_USER_CONFIG_PATH: /p/scratch/vbt/vbt-spack/vbt_spack_kernel/$KERNEL_VERSION
    DEPLOY_TYPE: "hpc"
  id_tokens:
    SITE_ID_TOKEN:
      aud: "https://gitlab.jsc.fz-juelich.de"
  rules:
    - if: $CI_COMMIT_TAG
  stage: release
  timeout: 72 hours
  tags:
    - juwels
    - jacamar
    - login
    - shell
  needs:
    - prep-hpc-environment-release
  script:
    - gcc --version
    - export FULL_PATH=$(pwd)
    - cd $CUSTOM_CI_BUILDS_DIR
    - cp -r $FULL_PATH $CUSTOM_CI_BUILDS_DIR
    - cd virtualbraintwin
    - module load StdEnv/2025
    - export TMPFILE=$(mktemp)
    - chmod +x ./installation/shared/vbt.sh
    - bash -c 'set -o pipefail && ./installation/shared/vbt.sh "use_cache.py" "./installation/" | tee "$TMPFILE"'
    - pwd
    - ls --all
    - cp $CUSTOM_CI_BUILDS_DIR/virtualbraintwin/installation/shared/.dedal.log $CUSTOM_CI_BUILDS_DIR/virtualbraintwin/build_cache_ubuntu_rocky.dedal.log
    - cp $CUSTOM_CI_BUILDS_DIR/virtualbraintwin/installation/shared/.generate_cache.log $CUSTOM_CI_BUILDS_DIR/virtualbraintwin/build_cache_ubuntu_rocky.generate_cache.log
    - export RESULT=$(grep . "$TMPFILE" | tail -n 2 | head -n 1)
    - cp $TMPFILE $CUSTOM_CI_BUILDS_DIR/virtualbraintwin/complete_log.txt
    - ls --all
    - |
      if [ "$RESULT" != "true" ]; then
       exit 1
      fi
  artifacts:
    when: always
    paths:
      - $CUSTOM_CI_BUILDS_DIR/virtualbraintwin/complete_log.txt
      - $CUSTOM_CI_BUILDS_DIR/virtualbraintwin/build_cache_ubuntu_rocky.dedal.log
      - $CUSTOM_CI_BUILDS_DIR/virtualbraintwin/build_cache_ubuntu_rocky.generate_cache.log
    expire_in: never

release-vbt-kernel:
  environment:
    name: caching-rocky
  needs:
    - install-vbt-spack-env-hpc
  variables:
    GIT_STRATEGY: none
    CUSTOM_CI_BUILDS_DIR: /p/scratch/vbt/vbt-spack/vbt_spack_kernel/$KERNEL_VERSION
    HOME: /p/scratch/vbt/vbt-spack/vbt_spack_kernel/$KERNEL_VERSION
    SPACK_USER_CONFIG_PATH: /p/scratch/vbt/vbt-spack/vbt_spack_kernel/$KERNEL_VERSION
    DEPLOY_TYPE: "hpc"
  id_tokens:
    SITE_ID_TOKEN:
      aud: "https://gitlab.jsc.fz-juelich.de"
  rules:
    - if: $CI_COMMIT_TAG
  stage: release
  timeout: 1 hours
  tags:
    - juwels
    - jacamar
    - login
    - shell
  script:
    - export FULL_PATH=$(pwd)
    - echo $FULL_PATH
    - cd $CUSTOM_CI_BUILDS_DIR
    - ls
    - echo $USER
    - cd ./virtualbraintwin/installation/hpc/
    - bash ./create_hpc_vbt_kernel.sh

cleanup-release-env:
  stage: release
  environment:
    name: caching-rocky
  tags:
    - juwels
    - jacamar
    - login
    - shell
  needs:
    - release-vbt-kernel
  rules:
    - if: $CI_COMMIT_TAG
  variables:
    GIT_STRATEGY: none
  script:
    - echo "Cleaning up project dir..."
    - rm -rf $CUSTOM_CI_BUILDS_DIR/$USER

sync_to_github:
  stage: sync
  environment:
    name: git-sync
  image: ubuntu:24.04
  tags:
    - $DOCKER_RUNNER_TAG
  only:
    - master
  before_script:
    - apt-get update
    - apt-get install -y git ca-certificates
  script:
    - git clone -b master https://oauth2:$GITLAB_TOKEN@gitlab.jsc.fz-juelich.de/virtualbraintwin/virtualbraintwin.git
    - cd virtualbraintwin
    - git remote add github https://$GITHUB_MIRROR_TOKEN@github.com/virtual-brain-twins/twin-distribution.git
    - git push github master:master --force


create-box:
  environment:
    name: caching-ubuntu
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $OPERATION == "release"'
  stage: release
  when: manual
  timeout: 3 hours
  tags:
    - vm-runner
  before_script:
    - echo "VirtualBox version:"
    - vboxmanage --version
    - echo "Vagrant version:"
    - vagrant --version
    # install VirtualBox and Vagrant on the Ci runner
    - chmod +x $CI_PROJECT_DIR/installation/shared/release/release_vagrant_box_tools.sh
    - $CI_PROJECT_DIR/installation/shared/release/release_vagrant_box_tools.sh
  script:
    # Output version to verify install
    - echo "VirtualBox version:"
    - vboxmanage --version
    - echo "Vagrant version:"
    - vagrant --version
    - cd $CI_PROJECT_DIR/installation/local/VM_user
  #    - vagrant up
  #    - cd /
  #    - vagrant package --base VM_vbt_user --output $BOX_NAME
  artifacts:
    paths:
      - $BOX_NAME
    expire_in: never

release-gitlab:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs:
    - release-vbt-kernel
  #    - create-box
  tags:
    - $DOCKER_RUNNER_TAG
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "running release_job"
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
  artifacts:
    paths:
      - $BOX_NAME
    expire_in: never
