stages:
  - test
  - build
  - release

variables:
  DEBIAN_FRONTEND: noninteractive

test-create-cache:
  rules:
    - if: '$CI_COMMIT_BRANCH != "master" && $CI_COMMIT_BRANCH != "dev"'
      when: always
    - when: never
  image: python:3.11
  stage: test
  timeout: 1 hours
  tags:
    - $DOCKER_RUNNER_TAG
  before_script:
    - chmod +x ./installation/local/shared/commons/bootstrap.sh
    - ./installation/local/shared/commons/bootstrap.sh
  script:
    - chmod +x ./installation/local/shared/vbt.sh
    - ./installation/local/shared/vbt.sh "create_cache.py" "./installation/local/"
    - mv ./installation/local/shared/.dedal.log .create_cache.dedal.log
    - mv ./installation/local/shared/.generate_cache.log .create_cache.generate_cache.log
  artifacts:
    paths:
      - .create_cache.dedal.log
      - .create_cache.generate_cache.log
    expire_in: 1 week

test-use-cache:
  environment:
    name: testing
  rules:
    - if: '$CI_COMMIT_BRANCH != "master" && $CI_COMMIT_BRANCH != "dev"'
      when: always
    - when: never
  image: python:3.11
  stage: test
  timeout: 1 hours
  tags:
    - $DOCKER_RUNNER_TAG
  before_script:
    - chmod +x ./installation/local/shared/commons/bootstrap.sh
    - ./installation/local/shared/commons/bootstrap.sh
  script:
    - chmod +x ./installation/local/shared/vbt.sh
    - ./installation/local/shared/vbt.sh "use_cache.py" "./installation/local/"
    - mv ./installation/local/shared/.dedal.log .use_cache.dedal.log
    - mv ./installation/local/shared/.generate_cache.log .use_cache.generate_cache.log
  artifacts:
    paths:
      - .use_cache.dedal.log
      - .use_cache.generate_cache.log
    expire_in: 1 week

build-cache-VM:
  id_tokens:
    SITE_ID_TOKEN:
      aud: "https://gitlab.jsc.fz-juelich.de"
  environment:
    name: caching
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $OPERATION == "cache"'
  image: ubuntu:24.04
  stage: build
  timeout: 48 hours
  tags:
    - juwels
    - jacamar
    - login
    - shell
  before_script:
    - apt-get update
    - chmod +x ./installation/local/shared/commons/bootstrap.sh
    - ./installation/local/shared/commons/bootstrap.sh
    - chmod +x ./installation/local/shared/release/release_vagrant_box_tools.sh
    - ./installation/local/shared/release/release_vagrant_box_tools.sh
  script:
    - echo "VirtualBox version:"
    - vboxmanage --version
    - echo "Vagrant version:"
    - vagrant --version
    - cd ../VM_cache
    - vagrant up
    - mv ./installation/local/shared/.dedal.log .build_cache_VM.dedal.log
    - mv ./installation/local/shared/.generate_cache.log .build_cache_VM.generate_cache.log
  artifacts:
    paths:
      - .build_cache_VM.dedal.log
      - .build_cache_VM.generate_cache.log
    expire_in: never

build-cache-docker:
  environment:
    name: caching-docker
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $OPERATION == "cache"'
  image: python:3.11
  stage: build
  timeout: 48 hours
  tags:
    - $DOCKER_RUNNER_TAG
  before_script:
    - chmod +x ./installation/local/shared/commons/bootstrap.sh
    - ./installation/local/shared/commons/bootstrap.sh
    - gcc --version
  script:
    - chmod +x ./installation/local/shared/vbt.sh
    - ./installation/local/shared/vbt.sh "create_cache.py" "./installation/local/"
    - mv ./installation/local/shared/.dedal.log .build_cache_docker.dedal.log
    - mv ./installation/local/shared/.generate_cache.log .build_cache_docker.generate_cache.log
  artifacts:
    paths:
      - .build_cache_docker.dedal.log
      - .build_cache_docker.generate_cache.log
    expire_in: never

create-box:
  environment:
    name: caching
  rules:
    - if: $CI_COMMIT_TAG
  image: ubuntu:24.04
  stage: release
  when: manual
  timeout: 3 hours
  tags:
    - $SHELL_RUNNER_TAG
  before_script:
    # install VirtualBox and Vagrant on the Ci runner
    - chmod +x ./installation/local/shared/commons/vagrant_box_tools.sh
    - ./installation/local/shared/commons/vagrant_box_tools.sh
  script:
      # Output version to verify install
    - echo "VirtualBox version:"
    - vboxmanage --version
    - echo "Vagrant version:"
    - vagrant --version
    - cd ../VM_user
    - vagrant up
    - cd /
    - vagrant package --base VM_vbt_user --output $BOX_NAME
  artifacts:
    paths:
      - $BOX_NAME
    expire_in: never

release-gitlab:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  needs: ["create-box"]
  tags:
    - $DOCKER_RUNNER_TAG
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo "running release_job"
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
  artifacts:
    paths:
      - $BOX_NAME
    expire_in: never
