stages:
  - test
  - build
  - release
  - hpcbuild 
  - hpctest

variables:
  DEBIAN_FRONTEND: noninteractive
  BOX_NAME: "vbt_debian12.box"
  SCHEDULER_PARAMETERS: "--account vbt"
  BASEPATH: "/p/project1/vbt/" #TODO: need better way to navigate

JSC_HPC_BUILD:
  environment:
    name: testing
  id_tokens:
    SITE_ID_TOKEN:
      aud: "https://gitlab.jsc.fz-juelich.de"

  stage: hpcbuild
  tags:
    - juwels
    - jacamar
    - login
    - shell
  rules:
    - if: '$CI_COMMIT_BRANCH == "dedalCiHPC"'
      when: on_success
    - when: never
  script:
    - usr=$(whoami) 

    - mkdir -p $BASEPATH/$usr  
    - cd $BASEPATH/$usr/

    - if [ -d "dedal" ]; then rm -rf dedal; fi  
    - git clone https://gitlab.ebrains.eu/ri/tech-hub/platform/esd/dedal.git  
    - cd dedal  
    - module load Python
    - python -m venv venv 
    - source venv/bin/activate 
    - pip install --upgrade pip   
    - pip install -e .[test]  # from dedal cicd script
    - pip install pytest-html # TBD need to see requirements.txt 
    # - export PATH="/p/home/jusers/$usr/$SYSTEMNAME/.local/bin:$PATH" 
    - pytest --disable-warnings  --html=report.html --self-contained-html 
    - deactivate
    - cd ..
    - if [ -d "dedal" ]; then rm -rf dedal; fi 

# JSC_HPC_test:
#   environment:
#     name: testing
#   id_tokens:
#     SITE_ID_TOKEN:
#       aud: "https://gitlab.jsc.fz-juelich.de"

#   stage: hpctest
#   tags:
#     - juwels
#     - jacamar
#     - compute
#     - slurm
#   rules:
#     - if: '$CI_COMMIT_BRANCH == "dedalCiHPC"'
#       when: on_success
#     - when: never
#   script:
#     - usr=$(whoami) 

#     - mkdir -p $BASEPATH/$usr  
#     - cd $BASEPATH/$usr/

#     - cd dedal  

#     - module load Python 
#     - export PATH="/p/home/jusers/$usr/juwels/.local/bin:$PATH" 
#     - pytest --disable-warnings  

test-create-cache:
  environment:
    name: testing
  rules:
    - if: '$CI_COMMIT_BRANCH == "dedalCiHPC"'
      when: never
    - if: '$CI_COMMIT_BRANCH != "master" && $CI_COMMIT_BRANCH != "dev"'
      when: always
    - when: never
  image: python:3.11
  stage: test
  timeout: 1 hours
  tags:
    - $DOCKER_RUNNER_TAG
  before_script:
    - chmod +x ./installation/local/shared/commons/bootstrap.sh
    - ./installation/local/shared/commons/bootstrap.sh
  script:
    - chmod +x ./installation/local/shared/vbt.sh
    - ./installation/local/shared/vbt.sh "create_cache.py" "./installation/local/"
    - mv ./installation/local/shared/.dedal.log .create_cache.dedal.log
    - mv ./installation/local/shared/.generate_cache.log .create_cache.generate_cache.log
  artifacts:
    paths:
      - .create_cache.dedal.log
      - .create_cache.generate_cache.log
    expire_in: 1 week

test-use-cache:
  environment:
    name: testing
  rules:
    - if: '$CI_COMMIT_BRANCH == "dedalCiHPC"'
      when: never
    - if: '$CI_COMMIT_BRANCH != "master" && $CI_COMMIT_BRANCH != "dev"'
      when: always
    - when: never
  image: python:3.11
  stage: test
  timeout: 1 hours
  tags:
    - $DOCKER_RUNNER_TAG
  before_script:
    - chmod +x ./installation/local/shared/commons/bootstrap.sh
    - ./installation/local/shared/commons/bootstrap.sh
  script:
    - chmod +x ./installation/local/shared/vbt.sh
    - ./installation/local/shared/vbt.sh "use_cache.py" "./installation/local/"
    - mv ./installation/local/shared/.dedal.log .use_cache.dedal.log
    - mv ./installation/local/shared/.generate_cache.log .use_cache.generate_cache.log
  artifacts:
    paths:
      - .use_cache.dedal.log
      - .use_cache.generate_cache.log
    expire_in: 1 week

build-cache:
  environment:
    name: caching
  rules:
    - if: '$CI_COMMIT_BRANCH == "dedalCiHPC"'
      when: never
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $OPERATION == "cache"'
  image: python:3.11
  stage: build
  timeout: 24 hours
  tags:
    - $DOCKER_RUNNER_TAG
  before_script:
    - chmod +x ./installation/local/shared/commons/bootstrap.sh
    - ./installation/local/shared/commons/bootstrap.sh
  script:
    - chmod +x ./installation/local/shared/vbt.sh
    - ./installation/local/shared/vbt.sh "create_cache.py" "./installation/local/"

create-box:
  environment:
    name: caching
  rules:
    - if: '$CI_COMMIT_BRANCH == "dedalCiHPC"'
      when: never
    - if: '$CI_COMMIT_TAG && $CI_COMMIT_BRANCH == "master"'
  image: ubuntu:24.04
  stage: release
  when: manual
  timeout: 3 hours
  tags:
    - $SHELL_RUNNER_TAG
  before_script:
    # install virtual box on the Ci runner
    - chmod +x ./installation/local/shared/commons/release_tools.sh
    - ./installation/local/shared/commons/release_tools.sh



    # install Vagrant on the Ci runner
  script:
    - echo "running release_job"
    - echo "VirtualBox version:"
    - vboxmanage --version
    - echo "Vagrant version:"
    - vagrant --version

  artifacts:
    paths:
      - $BOX_NAME
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
