services:
  guacamole-db:
    image: postgres:latest
    container_name: guacamole-db
    environment:
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: some_password
      POSTGRES_DB: guacamole_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql

  guacamole:
    image: guacamole/guacamole
    container_name: guacamole
    depends_on:
      - guacamole-db
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: guacamole-db
      POSTGRES_PORT: 5432
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: some_password

      OPENID_AUTHORIZATION_ENDPOINT: https://keycloak.codemart.ro/realms/TVB/protocol/openid-connect/auth
      OPENID_JWKS_ENDPOINT: https://keycloak.codemart.ro/realms/TVB/protocol/openid-connect/certs
      OPENID_ISSUER: https://keycloak.codemart.ro/realms/TVB
      OPENID_CLIENT_ID: guacamole-client
      OPENID_REDIRECT_URI: http://localhost:8080/guacamole
      EXTENSION_PRIORITY: "openid"

    ports:
      - "8080:8080"

  guacd:
    image: guacamole/guacd
    container_name: guacd

volumes:
  postgres_data:
